package lagarto;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mamaldonadobo
 */
public class FrmPiedra extends javax.swing.JFrame {

    int aleatorio;
    public FrmPiedra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPiedra = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnSpock = new javax.swing.JButton();
        btnLagarto = new javax.swing.JButton();
        btnTijera = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnPiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piedra.png"))); // NOI18N
        btnPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraActionPerformed(evt);
            }
        });

        btnPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papel.png"))); // NOI18N
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnSpock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spock.png"))); // NOI18N
        btnSpock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpockActionPerformed(evt);
            }
        });

        btnLagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/largartoo.png"))); // NOI18N
        btnLagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagartoActionPerformed(evt);
            }
        });

        btnTijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tijeras.png"))); // NOI18N
        btnTijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijeraActionPerformed(evt);
            }
        });

        btnNuevo.setText("De Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(btnLagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTijera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSpock, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSpock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLagarto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(btnTijera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aleatorio=(int)(Math.random()*5+1);
        System.out.print(aleatorio);
    }//GEN-LAST:event_formWindowOpened

    private void btnPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraActionPerformed
        if (aleatorio==1)
        {
            JOptionPane.showMessageDialog(null,"Piedra, empate");
        }
        if (aleatorio==2)
        {
            JOptionPane.showMessageDialog(null,"Papel! El papel envuelve la piedra, perdiste!");
        }
        if (aleatorio==3)
        {
            JOptionPane.showMessageDialog(null,"Tijeras! Piedra aplasta a tijeras, ganaste!");
        }
        if (aleatorio==4)
        {
            JOptionPane.showMessageDialog(null,"Lagarto! Piedra aplasta al lagarto, ganaste!");
        }
        if (aleatorio==5)
        {
            JOptionPane.showMessageDialog(null,"Spock! Spock vaporiza a la piedra, perdiste!");
        }
    }//GEN-LAST:event_btnPiedraActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        if (aleatorio==1)
        {
            JOptionPane.showMessageDialog(null,"Piedra, El papel envuelve la piedra, ganaste!");
        }
        if (aleatorio==2)
        {
            JOptionPane.showMessageDialog(null,"Papel!, empate");
        }
        if (aleatorio==3)
        {
            JOptionPane.showMessageDialog(null,"Tijeras! Tijeras cortan papel, perdiste!");
        }
        if (aleatorio==4)
        {
            JOptionPane.showMessageDialog(null,"Lagarto! Lagarto devora papel, perdiste!");
        }
        if (aleatorio==5)
        {
            JOptionPane.showMessageDialog(null,"Spock! Papel desautoriza a Spock, ganaste!");
        }
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnTijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijeraActionPerformed
        if (aleatorio==1)
        {
            JOptionPane.showMessageDialog(null,"Piedra! Piedra aplasta a tijeras, perdiste!");
        }
        if (aleatorio==2)
        {
            JOptionPane.showMessageDialog(null,"Papel! Tijeras cortan papel, ganaste");
        }
        if (aleatorio==3)
        {
            JOptionPane.showMessageDialog(null,"Tijeras! Empate");
        }
        if (aleatorio==4)
        {
            JOptionPane.showMessageDialog(null,"Lagarto! Tijeras decapitan Lagarto, ganaste!");
        }
        if (aleatorio==5)
        {
            JOptionPane.showMessageDialog(null,"Spock! Spock rompe tijeras, perdiste!");
        }
    }//GEN-LAST:event_btnTijeraActionPerformed

    private void btnLagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagartoActionPerformed
        if (aleatorio==1)
        {
            JOptionPane.showMessageDialog(null,"Piedra! Piedra aplasta a lagarto, perdiste!");
        }
        if (aleatorio==2)
        {
            JOptionPane.showMessageDialog(null,"Papel! Lagarto devora papel, ganaste");
        }
        if (aleatorio==3)
        {
            JOptionPane.showMessageDialog(null,"Tijeras! Tijeras decapitan Lagarto, perdiste");
        }
        if (aleatorio==4)
        {
            JOptionPane.showMessageDialog(null,"Lagarto! Empate");
        }
        if (aleatorio==5)
        {
            JOptionPane.showMessageDialog(null,"Spock! Lagarto envenena a spock, ganaste!");
        }
    }//GEN-LAST:event_btnLagartoActionPerformed

    private void btnSpockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpockActionPerformed
         if (aleatorio==1)
        {
            JOptionPane.showMessageDialog(null,"Piedra! Spock vaporiza piedra, ganaste!");
        }
        if (aleatorio==2)
        {
            JOptionPane.showMessageDialog(null,"Papel! Papel desautoriza a Stock, perdiste!");
        }
        if (aleatorio==3)
        {
            JOptionPane.showMessageDialog(null,"Tijeras! Spock rompe tijeras, ganaste!");
        }
        if (aleatorio==4)
        {
            JOptionPane.showMessageDialog(null,"Lagarto! Lagarto envenena a spock, perdiste!");
        }
        if (aleatorio==5)
        {
            JOptionPane.showMessageDialog(null,"Spock! Empate");
        }
    }//GEN-LAST:event_btnSpockActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        aleatorio=(int)(Math.random()*5+1);
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPiedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPiedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPiedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPiedra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPiedra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLagarto;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPiedra;
    private javax.swing.JButton btnSpock;
    private javax.swing.JButton btnTijera;
    // End of variables declaration//GEN-END:variables
}
